"""Tests for domain qualifier enrichment in the heuristic analyzer.

These tests verify _enrich_domain_qualifier() reads from DomainSignalLoader's
organic vocabulary (generated by Haiku from cluster labels). The loader is
mocked with representative qualifier groups per domain.
"""

from __future__ import annotations

from unittest.mock import MagicMock, patch

# Representative organic vocabularies for testing — these mirror what Haiku
# would generate from cluster labels, not the deleted static _DOMAIN_QUALIFIERS.
_TEST_BACKEND_VOCAB = {
    "auth": ["auth", "authentication", "login", "session", "oauth", "jwt", "token"],
    "api": ["api", "endpoint", "rest", "graphql", "route", "handler"],
    "database": ["database", "query", "migration", "orm", "schema", "sql"],
    "performance": ["cache", "performance", "latency", "optimization", "throughput"],
}
_TEST_FRONTEND_VOCAB = {
    "components": ["component", "widget", "ui", "render", "layout"],
    "state": ["state", "store", "redux", "context", "reactive"],
    "styling": ["css", "tailwind", "theme", "responsive", "animation"],
}
_TEST_DEVOPS_VOCAB = {
    "ci-cd": ["ci", "cd", "pipeline", "deploy", "build", "github-actions"],
    "infra": ["terraform", "docker", "kubernetes", "k8s", "container", "infrastructure"],
    "monitoring": ["monitoring", "alerting", "observability", "logging", "metrics"],
}


def _mock_loader_with_vocab(vocabs: dict[str, dict[str, list[str]]]):
    """Create a mock DomainSignalLoader with the given qualifier vocabularies."""
    mock_loader = MagicMock()
    mock_loader.get_qualifiers.side_effect = lambda domain: vocabs.get(domain, {})
    return mock_loader


def test_enrich_backend_auth():
    from app.services.heuristic_analyzer import _enrich_domain_qualifier

    loader = _mock_loader_with_vocab({"backend": _TEST_BACKEND_VOCAB})
    with patch("app.services.heuristic_analyzer.get_signal_loader", return_value=loader):
        result = _enrich_domain_qualifier(
            "backend",
            "implement jwt authentication middleware with session token refresh",
        )
    assert result == "backend: auth"


def test_enrich_backend_api():
    from app.services.heuristic_analyzer import _enrich_domain_qualifier

    loader = _mock_loader_with_vocab({"backend": _TEST_BACKEND_VOCAB})
    with patch("app.services.heuristic_analyzer.get_signal_loader", return_value=loader):
        result = _enrich_domain_qualifier(
            "backend",
            "design a rest api endpoint with graphql fallback handler",
        )
    assert result == "backend: api"


def test_enrich_no_match_returns_original():
    from app.services.heuristic_analyzer import _enrich_domain_qualifier

    loader = _mock_loader_with_vocab({"backend": _TEST_BACKEND_VOCAB})
    with patch("app.services.heuristic_analyzer.get_signal_loader", return_value=loader):
        result = _enrich_domain_qualifier(
            "backend",
            "refactor the logging system for better readability",
        )
    assert result == "backend"


def test_enrich_single_keyword_hit_enriches():
    """With threshold=1, a single keyword hit now enriches (previously required 2)."""
    from app.services.heuristic_analyzer import _enrich_domain_qualifier

    loader = _mock_loader_with_vocab({"backend": _TEST_BACKEND_VOCAB})
    with patch("app.services.heuristic_analyzer.get_signal_loader", return_value=loader):
        # "token" hits auth (1 hit) — now sufficient with threshold=1
        result = _enrich_domain_qualifier(
            "backend",
            "clean up the token validation logic",
        )
    assert result == "backend: auth"


def test_enrich_unknown_domain_returns_original():
    """Domain not in loader's cache returns plain domain."""
    from app.services.heuristic_analyzer import _enrich_domain_qualifier

    loader = _mock_loader_with_vocab({"backend": _TEST_BACKEND_VOCAB})
    with patch("app.services.heuristic_analyzer.get_signal_loader", return_value=loader):
        result = _enrich_domain_qualifier(
            "marketing",
            "implement jwt authentication middleware",
        )
    assert result == "marketing"


def test_enrich_already_qualified_returns_as_is():
    from app.services.heuristic_analyzer import _enrich_domain_qualifier

    loader = _mock_loader_with_vocab({"backend": _TEST_BACKEND_VOCAB})
    with patch("app.services.heuristic_analyzer.get_signal_loader", return_value=loader):
        result = _enrich_domain_qualifier(
            "backend: security",
            "implement jwt authentication",
        )
    assert result == "backend: security"


def test_enrich_frontend_components():
    from app.services.heuristic_analyzer import _enrich_domain_qualifier

    loader = _mock_loader_with_vocab({"frontend": _TEST_FRONTEND_VOCAB})
    with patch("app.services.heuristic_analyzer.get_signal_loader", return_value=loader):
        result = _enrich_domain_qualifier(
            "frontend",
            "create a reusable component with proper render lifecycle and layout grid",
        )
    assert result == "frontend: components"


def test_enrich_devops_infra():
    from app.services.heuristic_analyzer import _enrich_domain_qualifier

    loader = _mock_loader_with_vocab({"devops": _TEST_DEVOPS_VOCAB})
    with patch("app.services.heuristic_analyzer.get_signal_loader", return_value=loader):
        result = _enrich_domain_qualifier(
            "devops",
            "set up docker container orchestration with kubernetes deployment",
        )
    assert result == "devops: infra"


def test_enrich_picks_top_qualifier_by_hits():
    from app.services.heuristic_analyzer import _enrich_domain_qualifier

    loader = _mock_loader_with_vocab({"backend": _TEST_BACKEND_VOCAB})
    with patch("app.services.heuristic_analyzer.get_signal_loader", return_value=loader):
        # auth: oauth(1) + session(1) + authentication(1) + jwt(1) + token(1) = 5
        # api: endpoint(1) = 1
        result = _enrich_domain_qualifier(
            "backend",
            "implement oauth session authentication with jwt token endpoint",
        )
    assert result == "backend: auth"


def test_enrich_no_loader_returns_plain():
    """When DomainSignalLoader is not initialized, return plain domain."""
    from app.services.heuristic_analyzer import _enrich_domain_qualifier

    with patch("app.services.heuristic_analyzer.get_signal_loader", return_value=None):
        result = _enrich_domain_qualifier(
            "backend",
            "implement jwt authentication middleware",
        )
    assert result == "backend"
