"""add task_type_telemetry

Revision ID: 2f3b0645e24d
Revises: b3a7e9f4c2d1
Create Date: 2026-04-23 11:14:43.293687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3b0645e24d'
down_revision: Union[str, Sequence[str], None] = 'b3a7e9f4c2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_type_telemetry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('raw_prompt', sa.Text(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedbacks_optimization_id'))

    with op.batch_alter_table('global_patterns', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('source_cluster_ids',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('source_project_ids',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('avg_cluster_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('optimizations', schema=None) as batch_op:
        batch_op.alter_column('phase_weights_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_optimizations_created_at'))
        batch_op.drop_index(batch_op.f('ix_optimizations_domain'))
        batch_op.drop_index(batch_op.f('ix_optimizations_intent_label'))
        batch_op.drop_index(batch_op.f('ix_optimizations_overall_score'))
        batch_op.drop_index(batch_op.f('ix_optimizations_project_created'))
        batch_op.drop_index(batch_op.f('ix_optimizations_status'))
        batch_op.drop_index(batch_op.f('ix_optimizations_strategy_used'))
        batch_op.drop_index(batch_op.f('ix_optimizations_task_type'))

    with op.batch_alter_table('prompt_cluster', schema=None) as batch_op:
        batch_op.alter_column('weighted_member_sum',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.create_index('uq_prompt_cluster_domain_label', ['parent_id', 'label'], unique=True, sqlite_where=sa.text("state = 'domain'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_cluster', schema=None) as batch_op:
        batch_op.drop_index('uq_prompt_cluster_domain_label', sqlite_where=sa.text("state = 'domain'"))
        batch_op.alter_column('weighted_member_sum',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('optimizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_optimizations_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimizations_strategy_used'), ['strategy_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimizations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimizations_project_created'), ['project_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimizations_overall_score'), ['overall_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimizations_intent_label'), ['intent_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimizations_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimizations_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('phase_weights_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('global_patterns', schema=None) as batch_op:
        batch_op.alter_column('avg_cluster_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('source_project_ids',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('source_cluster_ids',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedbacks_optimization_id'), ['optimization_id'], unique=False)

    op.drop_table('task_type_telemetry')
    # ### end Alembic commands ###
