"""initial schema - all 9 tables

Revision ID: 42eace9b572e
Revises:
Create Date: 2026-03-15 18:17:02.467764

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '42eace9b572e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('github_user_id', sa.String(), nullable=True),
    sa.Column('github_login', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('linked_repos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('raw_prompt', sa.Text(), nullable=False),
    sa.Column('optimized_prompt', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('strategy_used', sa.String(), nullable=True),
    sa.Column('changes_summary', sa.Text(), nullable=True),
    sa.Column('score_clarity', sa.Float(), nullable=True),
    sa.Column('score_specificity', sa.Float(), nullable=True),
    sa.Column('score_structure', sa.Float(), nullable=True),
    sa.Column('score_faithfulness', sa.Float(), nullable=True),
    sa.Column('score_conciseness', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('scoring_mode', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('repo_full_name', sa.String(), nullable=True),
    sa.Column('codebase_context_snapshot', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('tokens_total', sa.Integer(), nullable=True),
    sa.Column('tokens_by_phase', sa.JSON(), nullable=True),
    sa.Column('context_sources', sa.JSON(), nullable=True),
    sa.Column('original_scores', sa.JSON(), nullable=True),
    sa.Column('score_deltas', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_file_index',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_full_name', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_sha', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('outline', sa.Text(), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_file_index_repo_full_name'), 'repo_file_index', ['repo_full_name'], unique=False)
    op.create_table('repo_index_meta',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_full_name', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('head_sha', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_affinities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('thumbs_up', sa.Integer(), nullable=False),
    sa.Column('thumbs_down', sa.Integer(), nullable=False),
    sa.Column('approval_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('optimization_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['optimization_id'], ['optimizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refinement_branches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('optimization_id', sa.String(), nullable=False),
    sa.Column('parent_branch_id', sa.String(), nullable=True),
    sa.Column('forked_at_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['optimization_id'], ['optimizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refinement_turns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('optimization_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('parent_version', sa.Integer(), nullable=True),
    sa.Column('refinement_request', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('deltas', sa.JSON(), nullable=True),
    sa.Column('deltas_from_original', sa.JSON(), nullable=True),
    sa.Column('strategy_used', sa.String(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['refinement_branches.id'], ),
    sa.ForeignKeyConstraint(['optimization_id'], ['optimizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refinement_turns')
    op.drop_table('refinement_branches')
    op.drop_table('feedbacks')
    op.drop_table('strategy_affinities')
    op.drop_table('repo_index_meta')
    op.drop_index(op.f('ix_repo_file_index_repo_full_name'), table_name='repo_file_index')
    op.drop_table('repo_file_index')
    op.drop_table('optimizations')
    op.drop_table('linked_repos')
    op.drop_table('github_tokens')
    # ### end Alembic commands ###
