"""add taxonomy engine tables and columns

Revision ID: 566d427e2067
Revises: fa5b21b07fd5
Create Date: 2026-03-21 03:16:47.957755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566d427e2067'
down_revision: Union[str, Sequence[str], None] = 'fa5b21b07fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomy_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('label_generated_at', sa.DateTime(), nullable=False),
    sa.Column('centroid_embedding', sa.LargeBinary(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('coherence', sa.Float(), nullable=False),
    sa.Column('separation', sa.Float(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('persistence', sa.Float(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('observations', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('umap_x', sa.Float(), nullable=True),
    sa.Column('umap_y', sa.Float(), nullable=True),
    sa.Column('umap_z', sa.Float(), nullable=True),
    sa.Column('color_hex', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['taxonomy_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_taxonomy_parent', 'taxonomy_nodes', ['parent_id'], unique=False)
    op.create_index('ix_taxonomy_persistence', 'taxonomy_nodes', ['persistence'], unique=False)
    op.create_index('ix_taxonomy_state', 'taxonomy_nodes', ['state'], unique=False)
    op.create_table('taxonomy_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('q_system', sa.Float(), nullable=False),
    sa.Column('q_coherence', sa.Float(), nullable=False),
    sa.Column('q_separation', sa.Float(), nullable=False),
    sa.Column('q_coverage', sa.Float(), nullable=False),
    sa.Column('q_dbcv', sa.Float(), nullable=False),
    sa.Column('operations', sa.Text(), nullable=False),
    sa.Column('nodes_created', sa.Integer(), nullable=False),
    sa.Column('nodes_retired', sa.Integer(), nullable=False),
    sa.Column('nodes_merged', sa.Integer(), nullable=False),
    sa.Column('nodes_split', sa.Integer(), nullable=False),
    sa.Column('tree_state', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('optimizations', sa.Column('taxonomy_node_id', sa.String(), nullable=True))
    op.add_column('optimizations', sa.Column('domain_raw', sa.String(), nullable=True))
    # FK constraints skipped — SQLite does not support ALTER TABLE ADD CONSTRAINT.
    # The FK relationship is declared in the ORM model; enforcement is not needed at this layer.
    op.add_column('pattern_families', sa.Column('taxonomy_node_id', sa.String(), nullable=True))
    op.add_column('pattern_families', sa.Column('domain_raw', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pattern_families', 'domain_raw')
    op.drop_column('pattern_families', 'taxonomy_node_id')
    op.drop_column('optimizations', 'domain_raw')
    op.drop_column('optimizations', 'taxonomy_node_id')
    op.drop_table('taxonomy_snapshots')
    op.drop_index('ix_taxonomy_state', table_name='taxonomy_nodes')
    op.drop_index('ix_taxonomy_persistence', table_name='taxonomy_nodes')
    op.drop_index('ix_taxonomy_parent', table_name='taxonomy_nodes')
    op.drop_table('taxonomy_nodes')
    # ### end Alembic commands ###
