"""add knowledge graph tables

Revision ID: 5ecb0e491693
Revises: 42eace9b572e
Create Date: 2026-03-18 18:37:16.181794

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5ecb0e491693'
down_revision: Union[str, Sequence[str], None] = '42eace9b572e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern_families',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('intent_label', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('centroid_embedding', sa.LargeBinary(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('pattern_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['pattern_families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('optimization_id', sa.String(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('meta_pattern_id', sa.String(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['pattern_families.id'], ),
    sa.ForeignKeyConstraint(['meta_pattern_id'], ['meta_patterns.id'], ),
    sa.ForeignKeyConstraint(['optimization_id'], ['optimizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('optimizations', sa.Column('intent_label', sa.String(), nullable=True))
    op.add_column('optimizations', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('optimizations', sa.Column('embedding', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('optimizations', 'embedding')
    op.drop_column('optimizations', 'domain')
    op.drop_column('optimizations', 'intent_label')
    op.drop_table('optimization_patterns')
    op.drop_table('meta_patterns')
    op.drop_table('pattern_families')
    # ### end Alembic commands ###
