"""add models_by_phase to optimization

Revision ID: d269ce918e9f
Revises: 60b437ebe4ef
Create Date: 2026-03-24 18:07:06.785153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd269ce918e9f'
down_revision: Union[str, Sequence[str], None] = '60b437ebe4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('optimizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('models_by_phase', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('optimizations', schema=None) as batch_op:
        batch_op.drop_column('models_by_phase')

    # ### end Alembic commands ###
