"""add composite index on optimization_patterns

Revision ID: fa5b21b07fd5
Revises: 5ecb0e491693
Create Date: 2026-03-18 21:30:54.754983

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fa5b21b07fd5'
down_revision: Union[str, Sequence[str], None] = '5ecb0e491693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_optpat_optid_rel', 'optimization_patterns', ['optimization_id', 'relationship'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_optpat_optid_rel', table_name='optimization_patterns')
    # ### end Alembic commands ###
