/**
 * Color utilities for taxonomy visualization.
 *
 * Replaces `constants/patterns.ts` — colors now come from the API
 * (generated by the backend's OKLab system). This module provides
 * only the score-to-color mapping and a fallback for null API colors.
 */

/** Default color for nodes/families without an API-assigned color. */
const FALLBACK_COLOR = '#7a7a9e';

/**
 * Domain-to-hex color map — used when the API returns a domain string
 * instead of a hex color (e.g. PatternFamily.domain for Navigator dots
 * and Inspector badges). Must stay in sync with backend OKLab palette.
 */
// Domain colors — electric neon palette, must NOT overlap with tier accents:
//   internal=#00e5ff (cyan), sampling=#22ff88 (green), passthrough=#fbbf24 (yellow)
const DOMAIN_COLORS: Record<string, string> = {
  backend: '#b44aff',   // electric violet
  frontend: '#ff6a00',  // electric orange
  database: '#00e0d0',  // electric teal
  security: '#ff2255',  // electric red-pink
  devops: '#3d9eff',    // electric blue
  fullstack: '#d946ef',  // electric magenta
  general: '#7a7a9e',   // dim gray
};

/** Score-to-color mapping using design system tokens. */
export function scoreColor(score: number | null): string {
  if (score == null || score <= 0) return 'var(--color-text-dim)';
  if (score >= 9.0) return 'var(--color-neon-green)';
  if (score >= 7.0) return 'var(--color-neon-cyan)';
  if (score >= 4.0) return 'var(--color-neon-yellow)';
  return 'var(--color-neon-red)';
}

/**
 * Resolve a taxonomy color. Accepts either:
 * - a hex color string (returned as-is)
 * - a domain name ("backend", "frontend", etc.) — resolved via DOMAIN_COLORS
 * - a free-form domain string ("frontend CSS architecture") — matched by keyword
 * - null/undefined — returns FALLBACK_COLOR
 */
export function taxonomyColor(color: string | null | undefined): string {
  if (!color) return FALLBACK_COLOR;
  // If it's a hex color, return directly
  if (color.startsWith('#')) return color;
  // Exact match first
  if (color in DOMAIN_COLORS) return DOMAIN_COLORS[color];
  // Keyword match: check if any known domain keyword appears in the string
  const lower = color.toLowerCase();
  for (const [domain, hex] of Object.entries(DOMAIN_COLORS)) {
    if (domain !== 'general' && lower.includes(domain)) return hex;
  }
  return FALLBACK_COLOR;
}

/** Q_system health color for StatusBar badge. */
export function qHealthColor(qSystem: number | null): string {
  if (qSystem == null) return 'var(--color-text-dim)';
  if (qSystem >= 0.8) return 'var(--color-neon-green)';
  if (qSystem >= 0.6) return 'var(--color-neon-cyan)';
  if (qSystem >= 0.4) return 'var(--color-neon-yellow)';
  return 'var(--color-neon-red)';
}

/** Cluster lifecycle state color for state filter tabs and badges. */
export function stateColor(state: string): string {
  const map: Record<string, string> = {
    candidate: '#7a7a9e',
    active: '#4d8eff',
    mature: '#a855f7',
    template: '#00e5ff',
    archived: '#2a2a3e',
  };
  return map[state] ?? '#7a7a9e';
}
