/**
 * Color utilities for taxonomy visualization.
 *
 * Domain colors are fetched from the API via the domain store
 * (generated by the backend's OKLab system). This module provides
 * score-to-color mapping, domain color delegation, and lifecycle
 * state colors.
 */

import { domainStore } from '$lib/stores/domains.svelte';

/** Highlight color for selected/hovered topology nodes. */
export const HIGHLIGHT_COLOR_HEX = '#00e5ff';

/** Similarity edge color for topology graph. */
export const SIMILARITY_EDGE_COLOR_HEX = '#00e5ff';

/** Score-to-color mapping using design system tokens. */
export function scoreColor(score: number | null): string {
  if (score == null || score <= 0) return 'var(--color-text-dim)';
  if (score >= 9.0) return 'var(--color-neon-green)';
  if (score >= 7.0) return 'var(--color-neon-cyan)';
  if (score >= 4.0) return 'var(--color-neon-yellow)';
  return 'var(--color-neon-red)';
}

/**
 * Resolve a taxonomy color. Delegates to the domain store for
 * API-driven color resolution. Accepts either:
 * - a hex color string (returned as-is)
 * - a domain name — resolved via domain store colors
 * - a free-form domain string — matched by keyword against known domains
 * - null/undefined — returns FALLBACK_COLOR
 */
export function taxonomyColor(color: string | null | undefined): string {
  return domainStore.colorFor(color);
}

/** Q_health color for StatusBar badge (member-weighted scale). */
export function qHealthColor(q: number | null): string {
  if (q == null) return 'var(--color-text-dim)';
  if (q >= 0.70) return 'var(--color-neon-green)';
  if (q >= 0.50) return 'var(--color-neon-cyan)';
  if (q >= 0.35) return 'var(--color-neon-yellow)';
  return 'var(--color-neon-red)';
}

/** Cluster lifecycle state color for state filter tabs and badges. */
export function stateColor(state: string): string {
  const map: Record<string, string> = {
    candidate: '#7a7a9e',
    active: '#4d8eff',
    mature: '#a855f7',
    archived: '#3a3a52',
    domain: '#c0a060',  // warm platinum — structural foundation (distinct from neon-yellow/passthrough #fbbf24)
  };
  return map[state] ?? '#7a7a9e';
}

/** Per-dimension colors for multi-line sparkline overlay. */
export const DIMENSION_COLORS: Record<string, string> = {
  clarity: 'var(--color-neon-cyan)',
  specificity: 'var(--color-neon-purple)',
  structure: 'var(--color-neon-blue)',
  faithfulness: 'var(--color-neon-green)',
  conciseness: 'var(--color-neon-orange)',
};
